### ISSUE TITLE
Template Integrity

### ISSUE THREAD

**Issue by timbohiatt** [GoogleCloudPlatform/dagify#26]
We need to develop a process of testing the integrity of all Templates on template load. It would be good to see these done as "Unit Tests" so that they can be run as part of a CICD pipeline. 

Tests of templates should ensure the following things: 

- All required fields are provided.
- All source fields are mapped.
- All listed rules exist within the code base. 
- All URL's resolve
- All referenced python packages and imports exist and are valid

**Comment by KonradSchieban** [comment]
YAML validation has been added to DAGify engine and to a Github Action on PR.
